CITIES = {
    "IN": [
        ("Maharashtra", "MH", ["Mumbai", "Pune", "Nagpur", "Nashik", "Aurangabad", "Thane", "Navi Mumbai"]),
        ("Karnataka", "KA", ["Bangalore", "Mysore", "Mangalore", "Hubli", "Belgaum"]),
        ("Tamil Nadu", "TN", ["Chennai", "Coimbatore", "Madurai", "Tiruchirappalli", "Salem"]),
        ("Telangana", "TG", ["Hyderabad", "Warangal", "Nizamabad"]),
        ("Delhi", "DL", ["New Delhi", "Delhi", "Dwarka", "Rohini"]),
        ("Gujarat", "GJ", ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Gandhinagar"]),
        ("West Bengal", "WB", ["Kolkata", "Howrah", "Durgapur", "Asansol"]),
        ("Uttar Pradesh", "UP", ["Lucknow", "Kanpur", "Noida", "Greater Noida", "Ghaziabad", "Agra", "Varanasi"]),
        ("Rajasthan", "RJ", ["Jaipur", "Jodhpur", "Udaipur", "Kota"]),
        ("Kerala", "KL", ["Kochi", "Thiruvananthapuram", "Kozhikode", "Thrissur"]),
        ("Punjab", "PB", ["Chandigarh", "Ludhiana", "Amritsar", "Jalandhar"]),
        ("Haryana", "HR", ["Gurugram", "Faridabad", "Panipat", "Ambala"]),
        ("Madhya Pradesh", "MP", ["Bhopal", "Indore", "Jabalpur", "Gwalior"]),
        ("Bihar", "BR", ["Patna", "Gaya", "Bhagalpur"]),
        ("Odisha", "OD", ["Bhubaneswar", "Cuttack", "Rourkela"]),
    ],
    "US": [
        ("California", "CA", ["San Francisco", "Los Angeles", "San Diego", "San Jose", "Oakland", "Palo Alto", "Mountain View", "Santa Monica", "Berkeley", "Irvine"]),
        ("New York", "NY", ["New York", "Brooklyn", "Buffalo", "Rochester", "Albany", "Yonkers"]),
        ("Texas", "TX", ["Austin", "Houston", "Dallas", "San Antonio", "Fort Worth", "Plano", "Irving"]),
        ("Washington", "WA", ["Seattle", "Bellevue", "Redmond", "Spokane", "Tacoma"]),
        ("Massachusetts", "MA", ["Boston", "Cambridge", "Worcester", "Springfield"]),
        ("Illinois", "IL", ["Chicago", "Aurora", "Naperville", "Evanston"]),
        ("Colorado", "CO", ["Denver", "Boulder", "Colorado Springs", "Aurora"]),
        ("Georgia", "GA", ["Atlanta", "Savannah", "Augusta", "Athens"]),
        ("Florida", "FL", ["Miami", "Orlando", "Tampa", "Jacksonville", "Fort Lauderdale"]),
        ("North Carolina", "NC", ["Raleigh", "Charlotte", "Durham", "Asheville"]),
        ("Pennsylvania", "PA", ["Philadelphia", "Pittsburgh", "Allentown"]),
        ("Virginia", "VA", ["Arlington", "Alexandria", "Richmond", "Virginia Beach"]),
        ("Oregon", "OR", ["Portland", "Eugene", "Salem", "Bend"]),
        ("Arizona", "AZ", ["Phoenix", "Scottsdale", "Tucson", "Tempe"]),
        ("Michigan", "MI", ["Detroit", "Ann Arbor", "Grand Rapids"]),
        ("New Jersey", "NJ", ["Newark", "Jersey City", "Princeton", "Hoboken"]),
    ],
    "CA": [
        ("Ontario", "ON", ["Toronto", "Ottawa", "Mississauga", "Hamilton", "Waterloo", "London"]),
        ("British Columbia", "BC", ["Vancouver", "Victoria", "Surrey", "Burnaby", "Kelowna"]),
        ("Quebec", "QC", ["Montreal", "Quebec City", "Laval", "Gatineau"]),
        ("Alberta", "AB", ["Calgary", "Edmonton", "Red Deer"]),
        ("Manitoba", "MB", ["Winnipeg", "Brandon"]),
        ("Nova Scotia", "NS", ["Halifax", "Sydney"]),
        ("Saskatchewan", "SK", ["Saskatoon", "Regina"]),
    ],
    "DE": [
        ("Bavaria", "BY", ["Munich", "Nuremberg", "Augsburg", "Regensburg"]),
        ("Berlin", "BE", ["Berlin", "Charlottenburg", "Mitte", "Kreuzberg"]),
        ("Hamburg", "HH", ["Hamburg", "Altona", "St. Pauli"]),
        ("Hesse", "HE", ["Frankfurt", "Wiesbaden", "Darmstadt", "Kassel"]),
        ("North Rhine-Westphalia", "NW", ["Cologne", "Düsseldorf", "Dortmund", "Essen", "Bonn", "Bielefeld"]),
        ("Baden-Württemberg", "BW", ["Stuttgart", "Karlsruhe", "Mannheim", "Freiburg", "Heidelberg"]),
        ("Saxony", "SN", ["Dresden", "Leipzig", "Chemnitz"]),
        ("Lower Saxony", "NI", ["Hannover", "Braunschweig", "Oldenburg"]),
    ],
    "GB": [
        ("England", "ENG", ["London", "Manchester", "Birmingham", "Liverpool", "Bristol", "Leeds", "Cambridge", "Oxford", "Brighton", "Reading"]),
        ("Scotland", "SCT", ["Edinburgh", "Glasgow", "Aberdeen", "Dundee"]),
        ("Wales", "WLS", ["Cardiff", "Swansea", "Newport"]),
        ("Northern Ireland", "NIR", ["Belfast", "Derry"]),
    ],
    "SG": [
        ("Central", "CG", ["Singapore", "Orchard", "Marina Bay", "Bugis"]),
        ("East", "EG", ["Tampines", "Bedok", "Pasir Ris"]),
        ("West", "WG", ["Jurong East", "Clementi", "Bukit Batok"]),
        ("North", "NG", ["Woodlands", "Yishun", "Sembawang"]),
    ],
    "AU": [
        ("New South Wales", "NSW", ["Sydney", "Newcastle", "Wollongong", "Parramatta"]),
        ("Victoria", "VIC", ["Melbourne", "Geelong", "Ballarat", "Bendigo"]),
        ("Queensland", "QLD", ["Brisbane", "Gold Coast", "Cairns", "Townsville"]),
        ("Western Australia", "WA", ["Perth", "Fremantle", "Mandurah"]),
        ("South Australia", "SA", ["Adelaide"]),
        ("Tasmania", "TAS", ["Hobart", "Launceston"]),
        ("ACT", "ACT", ["Canberra"]),
    ],
    "JP": [
        ("Tokyo", "13", ["Tokyo", "Shibuya", "Shinjuku", "Minato", "Setagaya", "Chiyoda"]),
        ("Osaka", "27", ["Osaka", "Umeda", "Namba", "Tennoji"]),
        ("Kanagawa", "14", ["Yokohama", "Kawasaki", "Kamakura"]),
        ("Aichi", "23", ["Nagoya"]),
        ("Hokkaido", "01", ["Sapporo", "Hakodate"]),
        ("Fukuoka", "40", ["Fukuoka", "Kitakyushu"]),
        ("Kyoto", "26", ["Kyoto"]),
        ("Hyogo", "28", ["Kobe"]),
    ],
    "KR": [
        ("Seoul", "11", ["Seoul", "Gangnam", "Jongno", "Mapo", "Yongsan"]),
        ("Busan", "26", ["Busan", "Haeundae", "Seomyeon"]),
        ("Gyeonggi", "41", ["Suwon", "Seongnam", "Goyang", "Yongin"]),
        ("Incheon", "28", ["Incheon"]),
        ("Daegu", "27", ["Daegu"]),
        ("Daejeon", "30", ["Daejeon"]),
    ],
    "AE": [
        ("Dubai", "DU", ["Dubai", "Downtown Dubai", "Dubai Marina", "JBR", "Business Bay"]),
        ("Abu Dhabi", "AZ", ["Abu Dhabi", "Al Ain", "Khalifa City"]),
        ("Sharjah", "SH", ["Sharjah"]),
        ("Ajman", "AJ", ["Ajman"]),
        ("Ras Al Khaimah", "RK", ["Ras Al Khaimah"]),
    ],
    "NL": [
        ("North Holland", "NH", ["Amsterdam", "Haarlem", "Zaandam"]),
        ("South Holland", "ZH", ["The Hague", "Rotterdam", "Leiden", "Delft"]),
        ("Utrecht", "UT", ["Utrecht", "Amersfoort"]),
        ("North Brabant", "NB", ["Eindhoven", "Tilburg", "'s-Hertogenbosch"]),
        ("Gelderland", "GE", ["Arnhem", "Nijmegen"]),
    ],
    "FR": [
        ("Île-de-France", "IDF", ["Paris", "Boulogne-Billancourt", "Saint-Denis", "Versailles"]),
        ("Provence-Alpes-Côte d'Azur", "PAC", ["Marseille", "Nice", "Cannes", "Toulon"]),
        ("Auvergne-Rhône-Alpes", "ARA", ["Lyon", "Grenoble", "Saint-Étienne"]),
        ("Occitanie", "OCC", ["Toulouse", "Montpellier"]),
        ("Nouvelle-Aquitaine", "NA", ["Bordeaux", "Limoges"]),
        ("Hauts-de-France", "HDF", ["Lille", "Amiens"]),
        ("Brittany", "BRE", ["Rennes", "Brest"]),
    ],
    "SE": [
        ("Stockholm", "ST", ["Stockholm", "Solna", "Sundbyberg", "Kista"]),
        ("Västra Götaland", "VG", ["Gothenburg", "Borås"]),
        ("Skåne", "SK", ["Malmö", "Lund", "Helsingborg"]),
        ("Uppsala", "UP", ["Uppsala"]),
        ("Östergötland", "OG", ["Linköping", "Norrköping"]),
    ],
    "CH": [
        ("Zurich", "ZH", ["Zurich", "Winterthur", "Uster"]),
        ("Geneva", "GE", ["Geneva", "Carouge"]),
        ("Bern", "BE", ["Bern", "Biel/Bienne"]),
        ("Basel-Stadt", "BS", ["Basel"]),
        ("Vaud", "VD", ["Lausanne", "Montreux", "Yverdon-les-Bains"]),
        ("Lucerne", "LU", ["Lucerne"]),
    ],
}

__all__ = ["CITIES"]