COUNTRIES = [
    {
        "name": "India",
        "code": "IN",
        "code3": "IND",
        "dial_code": "+91",
        "currency": "INR",
        "currency_symbol": "₹",
        "locale": "en_IN",
        "default_timezone": "Asia/Kolkata",
        "languages": ["en", "hi", "ta", "te", "bn"],
        "primary_language": "hi",
    },
    {
        "name": "United States",
        "code": "US",
        "code3": "USA",
        "dial_code": "+1",
        "currency": "USD",
        "currency_symbol": "$",
        "locale": "en_US",
        "default_timezone": "America/New_York",
        "languages": ["en", "es"],
        "primary_language": "en",
    },
    {
        "name": "Canada",
        "code": "CA",
        "code3": "CAN",
        "dial_code": "+1",
        "currency": "CAD",
        "currency_symbol": "C$",
        "locale": "en_CA",
        "default_timezone": "America/Toronto",
        "languages": ["en", "fr"],
        "primary_language": "en",
    },
    {
        "name": "Germany",
        "code": "DE",
        "code3": "DEU",
        "dial_code": "+49",
        "currency": "EUR",
        "currency_symbol": "€",
        "locale": "de_DE",
        "default_timezone": "Europe/Berlin",
        "languages": ["de", "en"],
        "primary_language": "de",
    },
    {
        "name": "United Kingdom",
        "code": "GB",
        "code3": "GBR",
        "dial_code": "+44",
        "currency": "GBP",
        "currency_symbol": "£",
        "locale": "en_GB",
        "default_timezone": "Europe/London",
        "languages": ["en"],
        "primary_language": "en",
    },
    {
        "name": "Singapore",
        "code": "SG",
        "code3": "SGP",
        "dial_code": "+65",
        "currency": "SGD",
        "currency_symbol": "S$",
        "locale": "en_SG",
        "default_timezone": "Asia/Singapore",
        "languages": ["en", "zh", "ms", "ta"],
        "primary_language": "en",
    },
    {
        "name": "Australia",
        "code": "AU",
        "code3": "AUS",
        "dial_code": "+61",
        "currency": "AUD",
        "currency_symbol": "A$",
        "locale": "en_AU",
        "default_timezone": "Australia/Sydney",
        "languages": ["en"],
        "primary_language": "en",
    },
    {
        "name": "Japan",
        "code": "JP",
        "code3": "JPN",
        "dial_code": "+81",
        "currency": "JPY",
        "currency_symbol": "¥",
        "locale": "ja_JP",
        "default_timezone": "Asia/Tokyo",
        "languages": ["ja", "en"],
        "primary_language": "ja",
    },
    {
        "name": "South Korea",
        "code": "KR",
        "code3": "KOR",
        "dial_code": "+82",
        "currency": "KRW",
        "currency_symbol": "₩",
        "locale": "ko_KR",
        "default_timezone": "Asia/Seoul",
        "languages": ["ko", "en"],
        "primary_language": "ko",
    },
    {
        "name": "United Arab Emirates",
        "code": "AE",
        "code3": "ARE",
        "dial_code": "+971",
        "currency": "AED",
        "currency_symbol": "د.إ",
        "locale": "ar_AE",
        "default_timezone": "Asia/Dubai",
        "languages": ["ar", "en"],
        "primary_language": "ar",
    },
    {
        "name": "Netherlands",
        "code": "NL",
        "code3": "NLD",
        "dial_code": "+31",
        "currency": "EUR",
        "currency_symbol": "€",
        "locale": "nl_NL",
        "default_timezone": "Europe/Amsterdam",
        "languages": ["nl", "en"],
        "primary_language": "nl",
    },
    {
        "name": "France",
        "code": "FR",
        "code3": "FRA",
        "dial_code": "+33",
        "currency": "EUR",
        "currency_symbol": "€",
        "locale": "fr_FR",
        "default_timezone": "Europe/Paris",
        "languages": ["fr", "en"],
        "primary_language": "fr",
    },
    {
        "name": "Sweden",
        "code": "SE",
        "code3": "SWE",
        "dial_code": "+46",
        "currency": "SEK",
        "currency_symbol": "kr",
        "locale": "sv_SE",
        "default_timezone": "Europe/Stockholm",
        "languages": ["sv", "en"],
        "primary_language": "sv",
    },
    {
        "name": "Switzerland",
        "code": "CH",
        "code3": "CHE",
        "dial_code": "+41",
        "currency": "CHF",
        "currency_symbol": "CHF",
        "locale": "de_CH",
        "default_timezone": "Europe/Zurich",
        "languages": ["de", "fr", "it", "en"],
        "primary_language": "de",
    },
]

__all__ = ["COUNTRIES"]