FIRST_NAMES_BY_COUNTRY = {
    "IN": ["Aarav", "Vihaan", "Aditya", "Arjun", "Rohan", "Krishna", "Ishaan", "Reyansh", "Ayaan", "Karan",
           "Ananya", "Diya", "Saanvi", "Aanya", "Pari", "Aadhya", "Khushi", "Myra", "Riya", "Avni",
           "Vikram", "Rohit", "Priya", "Neha", "Rahul", "Pooja", "Amit", "Sneha", "Sandeep", "Anjali"],
    "US": ["James", "John", "Robert", "Michael", "William", "David", "Richard", "Joseph", "Thomas", "Christopher",
           "Mary", "Patricia", "Jennifer", "Linda", "Elizabeth", "Barbara", "Susan", "Jessica", "Sarah", "Karen",
           "Daniel", "Matthew", "Anthony", "Mark", "Donald", "Steven", "Paul", "Andrew", "Joshua", "Kenneth"],
    "CA": ["Liam", "Noah", "Ethan", "Oliver", "Lucas", "Mason", "Logan", "James", "Benjamin", "Henry",
           "Emma", "Olivia", "Charlotte", "Amelia", "Mia", "Sophia", "Isabella", "Ava", "Charlotte", "Harper"],
    "DE": ["Lukas", "Felix", "Maximilian", "Jonas", "Paul", "Leon", "Finn", "Luis", "Niklas", "Tim",
           "Mia", "Emma", "Hannah", "Lea", "Lina", "Anna", "Marie", "Sophie", "Laura", "Lena"],
    "GB": ["Oliver", "George", "Harry", "Jack", "Jacob", "Noah", "Charlie", "Muhammad", "Thomas", "Oscar",
           "Olivia", "Amelia", "Isla", "Ava", "Emily", "Jessica", "Ella", "Mia", "Sophia", "Grace"],
    "SG": ["Wei", "Jun", "Hui", "Ming", "Lin", "Jian", "Hafiz", "Aisyah", "Rina", "Nadia",
           "Benjamin", "Ethan", "Ryan", "Jayden", "Lucas"],
    "AU": ["Oliver", "William", "Jack", "Noah", "Thomas", "James", "Lucas", "Henry", "Ethan", "Joshua",
           "Charlotte", "Olivia", "Amelia", "Isla", "Mia", "Ava", "Grace", "Sophia", "Emily", "Ruby"],
    "JP": ["Haruto", "Yuto", "Sota", "Yuki", "Hayato", "Ren", "Kaito", "Sora", "Minato", "Ryota",
           "Yui", "Hina", "Rio", "Mei", "Sakura", "Aoi", "Koharu", "Mio", "Yuna", "Akari"],
    "KR": ["Min-jun", "Seo-jun", "Do-yoon", "Ha-joon", "Si-woo", "Joon", "Ji-ho", "Min-ho", "Tae-hyun", "Hyun-woo",
           "Seo-yeon", "Min-seo", "Ji-woo", "Ye-jin", "Soo-yeon", "Ye-rim", "Ji-hye", "Min-ji", "Eun-ji", "Yu-jin"],
    "AE": ["Mohammed", "Ahmed", "Ali", "Omar", "Khalid", "Hassan", "Saif", "Rashid", "Hamdan", "Sultan",
           "Fatima", "Aisha", "Maryam", "Noora", "Layla", "Hala", "Reem", "Sara", "Noura", "Shaikha"],
    "NL": ["Daan", "Sem", "Lucas", "Finn", "Levi", "Noah", "Liam", "Milan", "Thijs", "Sam",
           "Emma", "Julia", "Mila", "Tess", "Sophie", "Zoë", "Anna", "Eva", "Lotte", "Nora"],
    "FR": ["Lucas", "Hugo", "Léo", "Louis", "Gabriel", "Arthur", "Jules", "Nathan", "Ethan", "Tom",
           "Emma", "Jade", "Louise", "Alice", "Chloé", "Lina", "Léa", "Manon", "Rose", "Anna"],
    "SE": ["Lucas", "William", "Hugo", "Liam", "Oliver", "Oscar", "Elias", "Axel", "Leo", "Adam",
           "Alice", "Maja", "Wilma", "Olivia", "Astrid", "Ella", "Ebba", "Alma", "Saga", "Julia"],
    "CH": ["Lukas", "Noah", "Leon", "Tim", "Julian", "Maximilian", "Nico", "Florian", "Elia", "Robin",
           "Mia", "Emma", "Anna", "Lara", "Sara", "Laura", "Lina", "Nina", "Jana", "Alina"],
}

LAST_NAMES_BY_COUNTRY = {
    "IN": ["Sharma", "Verma", "Patel", "Kumar", "Singh", "Gupta", "Iyer", "Reddy", "Nair", "Khan",
           "Mukherjee", "Chatterjee", "Banerjee", "Joshi", "Mehta", "Shah", "Desai", "Kapoor", "Bhat", "Rao"],
    "US": ["Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Miller", "Davis", "Rodriguez", "Martinez",
           "Hernandez", "Lopez", "Gonzalez", "Wilson", "Anderson", "Thomas", "Taylor", "Moore", "Jackson", "Martin"],
    "CA": ["Smith", "Brown", "Tremblay", "Martin", "Roy", "Wilson", "MacDonald", "Johnson", "Thompson", "Anderson",
           "Lee", "Walker", "Hall", "Young", "King"],
    "DE": ["Müller", "Schmidt", "Schneider", "Fischer", "Weber", "Meyer", "Wagner", "Becker", "Schulz", "Hoffmann",
           "Schäfer", "Koch", "Bauer", "Richter", "Klein"],
    "GB": ["Smith", "Jones", "Taylor", "Brown", "Wilson", "Evans", "Walker", "Johnson", "Wright", "Roberts",
           "Thompson", "Hall", "Clarke", "Edwards", "Mitchell"],
    "SG": ["Tan", "Lim", "Lee", "Ng", "Wong", "Goh", "Chua", "Chan", "Koh", "Ong",
           "Chen", "Lin", "Wang", "Soh", "Tay"],
    "AU": ["Smith", "Jones", "Williams", "Brown", "Wilson", "Taylor", "Johnson", "White", "Martin", "Anderson",
           "Thompson", "Nguyen", "Walker", "Harris", "Lee"],
    "JP": ["Sato", "Suzuki", "Takahashi", "Tanaka", "Watanabe", "Ito", "Yamamoto", "Nakamura", "Kobayashi", "Kato",
           "Yoshida", "Yamada", "Sasaki", "Yamaguchi", "Matsumoto"],
    "KR": ["Kim", "Lee", "Park", "Choi", "Jung", "Kang", "Jo", "Yoon", "Jang", "Lim",
           "Han", "Shin", "Seo", "Kwon", "Hwang"],
    "AE": ["Al Maktoum", "Al Nahyan", "Al Mazrouei", "Al Suwaidi", "Al Ketbi", "Al Dhaheri", "Al Ameri", "Al Hosani", "Al Kaabi", "Al Hammadi",
           "Al Falasi", "Al Marzooqi", "Al Shehhi", "Ali", "Khan"],
    "NL": ["De Jong", "Jansen", "De Vries", "Van den Berg", "Van Dijk", "Bakker", "Visser", "Smit", "Meijer", "De Boer",
           "Mulder", "De Groot", "Bos", "Vos", "Peters"],
    "FR": ["Martin", "Bernard", "Dubois", "Thomas", "Robert", "Richard", "Petit", "Durand", "Leroy", "Moreau",
           "Simon", "Laurent", "Lefebvre", "Michel", "Roux"],
    "SE": ["Andersson", "Johansson", "Karlsson", "Nilsson", "Eriksson", "Larsson", "Olsson", "Persson", "Svensson", "Gustafsson",
           "Pettersson", "Jonsson", "Jansson", "Hansson", "Bengtsson"],
    "CH": ["Müller", "Meier", "Huber", "Schmid", "Keller", "Weber", "Fischer", "Steiner", "Brunner", "Bauer",
           "Frei", "Berger", "Wyss", "Kunz", "Gerber"],
}

__all__ = ["FIRST_NAMES_BY_COUNTRY", "LAST_NAMES_BY_COUNTRY"]