SKILLS = {
    "Programming Languages": {
        "General Purpose": [
            "Python", "Java", "C", "C++", "C#", "Go", "Rust", "Ruby", "PHP", "Perl",
            "Scala", "Kotlin", "Swift", "Objective-C", "Dart", "Lua", "Haskell", "Elixir",
            "Clojure", "Erlang", "F#", "Julia", "R", "MATLAB", "Groovy", "TypeScript", "JavaScript",
        ],
        "Systems": ["C", "C++", "Rust", "Go", "Zig", "Ada", "Assembly"],
        "JVM": ["Java", "Kotlin", "Scala", "Groovy", "Clojure"],
        "Scripting": ["Python", "Ruby", "Perl", "Lua", "Bash", "PowerShell"],
        "Mobile": ["Swift", "Kotlin", "Objective-C", "Dart", "Java"],
        "Functional": ["Haskell", "Elixir", "Erlang", "Clojure", "F#", "OCaml"],
    },
    "Frontend": {
        "Frameworks": ["React", "Vue.js", "Angular", "Svelte", "Solid.js", "Ember.js", "Backbone.js", "Preact", "Alpine.js", "Qwik"],
        "State Management": ["Redux", "MobX", "Zustand", "Recoil", "Vuex", "Pinia", "NgRx", "XState"],
        "Styling": ["CSS", "Sass", "Less", "Tailwind CSS", "Bootstrap", "Material UI", "Chakra UI", "Styled Components", "Emotion", "PostCSS"],
        "Build Tools": ["Webpack", "Vite", "Rollup", "Parcel", "esbuild", "Turbopack", "Babel", "SWC"],
        "Testing": ["Jest", "Mocha", "Chai", "Cypress", "Playwright", "Vitest", "Testing Library", "Puppeteer"],
        "Rendering": ["Next.js", "Nuxt.js", "Remix", "SvelteKit", "Astro", "Gatsby", "React Native Web"],
    },
    "Backend": {
        "Frameworks": ["Django", "Flask", "FastAPI", "Express.js", "NestJS", "Spring Boot", "Spring", "Ruby on Rails", "Laravel", "ASP.NET", "ASP.NET Core", "Phoenix", "Gin", "Echo", "Fiber"],
        "API Design": ["REST", "GraphQL", "gRPC", "WebSockets", "Webhooks", "tRPC", "OpenAPI", "AsyncAPI"],
        "Authentication": ["OAuth 2.0", "OpenID Connect", "SAML", "JWT", "Auth0", "Okta", "Firebase Auth", "Keycloak"],
        "Message Queues": ["RabbitMQ", "Apache Kafka", "AWS SQS", "Google Pub/Sub", "Redis Streams", "NATS", "ActiveMQ"],
        "Search": ["Elasticsearch", "Apache Solr", "Meilisearch", "Algolia", "Typesense", "OpenSearch"],
        "Web Servers": ["Nginx", "Apache", "Caddy", "HAProxy", "Envoy", "Traefik"],
    },
    "Mobile": {
        "Cross Platform": ["React Native", "Flutter", "Xamarin", "Ionic", "Cordova", "Kotlin Multiplatform"],
        "iOS": ["Swift", "SwiftUI", "UIKit", "Combine", "Core Data", "ARKit", "CoreML"],
        "Android": ["Kotlin", "Jetpack Compose", "Android SDK", "RxJava", "Dagger", "Hilt", "Room"],
        "Tools": ["Xcode", "Android Studio", "Gradle", "Fastlane", "CocoaPods"],
    },
    "Databases": {
        "Relational": ["PostgreSQL", "MySQL", "MariaDB", "SQL Server", "Oracle", "SQLite", "Amazon RDS", "Amazon Aurora"],
        "NoSQL Document": ["MongoDB", "Couchbase", "Amazon DocumentDB", "Firestore", "RethinkDB"],
        "NoSQL Key-Value": ["Redis", "Memcached", "Amazon DynamoDB", "Aerospike"],
        "NoSQL Wide Column": ["Apache Cassandra", "ScyllaDB", "HBase"],
        "NoSQL Graph": ["Neo4j", "Amazon Neptune", "JanusGraph", "ArangoDB"],
        "Time Series": ["InfluxDB", "TimescaleDB", "Prometheus", "QuestDB", "OpenTSDB"],
        "Search Engines": ["Elasticsearch", "Solr", "Meilisearch"],
        "Vector": ["Pinecone", "Weaviate", "Milvus", "Qdrant", "Chroma", "pgvector", "FAISS"],
    },
    "Cloud & DevOps": {
        "Public Cloud": ["AWS", "Google Cloud Platform", "Microsoft Azure", "DigitalOcean", "Linode", "Vultr", "Oracle Cloud", "IBM Cloud"],
        "Containers": ["Docker", "Kubernetes", "Podman", "containerd", "LXC", "OpenShift", "Rancher", "Helm"],
        "CI/CD": ["Jenkins", "GitHub Actions", "GitLab CI", "CircleCI", "Travis CI", "Bitbucket Pipelines", "Argo CD", "Spinnaker"],
        "IaC": ["Terraform", "Pulumi", "Ansible", "Chef", "Puppet", "CloudFormation", "Packer"],
        "Monitoring": ["Prometheus", "Grafana", "Datadog", "New Relic", "Splunk", "Elastic Stack", "Honeycomb", "Sentry", "PagerDuty"],
        "Service Mesh": ["Istio", "Linkerd", "Consul", "Envoy"],
        "Serverless": ["AWS Lambda", "Google Cloud Functions", "Azure Functions", "Cloudflare Workers", "Vercel", "Netlify"],
    },
    "AI/ML & Data": {
        "ML Frameworks": ["TensorFlow", "PyTorch", "Keras", "scikit-learn", "XGBoost", "LightGBM", "CatBoost", "JAX", "Hugging Face Transformers", "Fastai"],
        "LLM": ["OpenAI API", "Anthropic API", "Claude API", "GPT-4", "LLaMA", "Mistral", "RAG", "LangChain", "LlamaIndex", "Prompt Engineering", "Fine-tuning"],
        "NLP": ["spaCy", "NLTK", "Hugging Face", "Word2Vec", "BERT", "Transformers", "Tokenization", "Sentiment Analysis", "Named Entity Recognition"],
        "Computer Vision": ["OpenCV", "YOLO", "Detectron", "Pillow", "MediaPipe", "MMDetection", "Image Segmentation", "OCR"],
        "Data Processing": ["Pandas", "NumPy", "Polars", "Dask", "Apache Spark", "Apache Beam", "PySpark"],
        "Data Visualization": ["Matplotlib", "Seaborn", "Plotly", "Bokeh", "D3.js", "Tableau", "Power BI", "Looker", "Grafana"],
        "MLOps": ["MLflow", "Kubeflow", "SageMaker", "Vertex AI", "Weights & Biases", "Comet", "BentoML", "Ray"],
        "Statistical": ["R", "SAS", "SPSS", "Bayesian Inference", "Time Series Analysis", "A/B Testing", "Causal Inference"],
    },
    "Security": {
        "Application Security": ["OWASP Top 10", "Snyk", "Veracode", "Checkmarx", "Burp Suite", "Static Analysis", "Dynamic Analysis"],
        "Network Security": ["Firewalls", "Wireshark", "Nmap", "IDS/IPS", "VPN", "Zero Trust", "Network Segmentation"],
        "Cryptography": ["TLS/SSL", "PKI", "AES", "RSA", "ECC", "Hashing", "Digital Signatures", "Symmetric Encryption"],
        "Identity": ["OAuth", "SAML", "OpenID Connect", "Active Directory", "LDAP", "MFA", "SSO"],
        "Compliance": ["SOC 2", "GDPR", "HIPAA", "PCI DSS", "ISO 27001", "FedRAMP", "CCPA"],
        "Offensive": ["Penetration Testing", "Bug Bounty", "Metasploit", "OSINT", "Social Engineering"],
        "Cloud Security": ["AWS Security", "Azure Security", "GCP Security", "Cloud Security Posture Management", "CSPM"],
    },
    "Engineering Practices": {
        "Version Control": ["Git", "GitHub", "GitLab", "Bitbucket", "SVN", "Mercurial"],
        "Methodologies": ["Agile", "Scrum", "Kanban", "SAFe", "Lean", "XP", "DevOps"],
        "Testing": ["Unit Testing", "Integration Testing", "End-to-End Testing", "TDD", "BDD", "Contract Testing", "Performance Testing", "Load Testing"],
        "Code Quality": ["Code Review", "Static Analysis", "Linting", "Refactoring", "Design Patterns", "Clean Code", "SonarQube"],
        "Architecture": ["Microservices", "Monolith", "Event-Driven", "Serverless", "Hexagonal Architecture", "CQRS", "Event Sourcing", "Domain-Driven Design"],
        "Documentation": ["Technical Writing", "API Documentation", "Architecture Diagrams", "ADRs"],
    },
    "Soft Skills": {
        "Leadership": ["Team Leadership", "Coaching", "Mentoring", "Strategic Planning", "Vision Setting"],
        "Communication": ["Public Speaking", "Technical Writing", "Stakeholder Management", "Cross-functional Collaboration", "Conflict Resolution"],
        "Product": ["Product Sense", "User Empathy", "Roadmap Planning", "User Research", "Data-Driven Decision Making"],
        "Design": ["User Experience Design", "User Interface Design", "Visual Design", "Interaction Design", "Design Systems", "Figma", "Sketch", "Adobe XD"],
        "Business": ["Strategy", "Negotiation", "Financial Modeling", "Market Analysis", "Go-to-Market Strategy"],
    },
    "Emerging Tech": {
        "Blockchain": ["Ethereum", "Solidity", "Smart Contracts", "Web3.js", "Ethers.js", "Hardhat", "Truffle", "IPFS", "NFTs", "DeFi", "Rust (Solana)", "Move (Aptos)"],
        "Quantum": ["Qiskit", "Cirq", "Quantum Computing", "Q#", "Quantum Algorithms"],
        "AR/VR": ["Unity", "Unreal Engine", "ARKit", "ARCore", "OpenXR", "WebXR", "Three.js"],
        "IoT": ["Arduino", "Raspberry Pi", "MQTT", "Embedded C", "FreeRTOS", "Zephyr", "Edge Computing"],
        "Robotics": ["ROS", "ROS2", "Gazebo", "SLAM", "Computer Vision", "Motion Planning", "Control Systems", "Reinforcement Learning"],
        "Autonomous Systems": ["Self-Driving Cars", "Sensor Fusion", "LIDAR", "Path Planning", "Drone Programming", "PX4"],
    },
    "Industry Specific": {
        "FinTech": ["Payment Processing", "PCI Compliance", "Risk Modeling", "Trading Systems", "KYC/AML", "Ledger Systems", "Fraud Detection"],
        "HealthTech": ["HL7 FHIR", "DICOM", "EHR Systems", "HIPAA Compliance", "Clinical Trials", "Genomics", "Bioinformatics"],
        "EdTech": ["LMS", "SCORM", "xAPI", "Adaptive Learning", "Content Authoring", "Video Streaming"],
        "Gaming": ["Unity", "Unreal Engine", "Game Physics", "Shader Programming", "OpenGL", "Vulkan", "DirectX", "Multiplayer Networking", "Procedural Generation"],
        "Aerospace": ["MATLAB/Simulink", "DO-178C", "Flight Software", "GNSS", "Mission Control", "STK", "Orbital Mechanics"],
    },
    "Tools & Productivity": {
        "IDEs": ["VS Code", "IntelliJ IDEA", "PyCharm", "WebStorm", "GoLand", "Xcode", "Android Studio", "Visual Studio", "Sublime Text", "Vim", "Emacs"],
        "Project Management": ["Jira", "Linear", "Asana", "Notion", "Trello", "Monday.com", "Confluence"],
        "Communication": ["Slack", "Microsoft Teams", "Zoom", "Google Meet", "Discord", "Loom"],
        "Design": ["Figma", "Sketch", "Adobe XD", "Photoshop", "Illustrator", "InVision", "Principle", "Framer"],
    },
    "Data Engineering": {
        "ETL/ELT": ["Apache Airflow", "dbt", "Talend", "Informatica", "AWS Glue", "Azure Data Factory"],
        "Streaming": ["Apache Kafka", "Apache Flink", "Apache Storm", "Kinesis", "Spark Streaming"],
        "Warehousing": ["Snowflake", "Amazon Redshift", "Google BigQuery", "Databricks", "Azure Synapse", "ClickHouse"],
        "Orchestration": ["Airflow", "Prefect", "Dagster", "Luigi", "Argo Workflows"],
        "Formats": ["Parquet", "ORC", "Avro", "JSON", "Protobuf", "CSV"],
    },
    "Web3 Specific": {
        "Smart Contract Languages": ["Solidity", "Vyper", "Cairo", "Move", "Rust (Solana)"],
        "Ethereum Ecosystem": ["EVM", "ERC-20", "ERC-721", "ERC-1155", "EIP-2981", "OpenZeppelin", "Hardhat", "Foundry"],
        "Layer 2": ["Optimism", "Arbitrum", "Polygon", "zkSync", "StarkNet", "Base"],
        "Wallets": ["MetaMask", "WalletConnect", "Phantom", "Rainbow"],
        "NFT": ["OpenSea", "IPFS", "ERC-721", "ERC-1155", "Metadata Standards"],
    },
}

__all__ = ["SKILLS"]
